stages: 
- sonar

#=================== Sonar Stage ===================
# Sonar Template
.sonar-template: &sonar-definition
  stage: sonar
  tags:
    - docker
  when: always
  before_script:
    - cp -R /home/repository/binaries.sonarsource.com/sonar-scanner-cli/$SONAR_CLI_VER sonar-scanner
  script: 
    - |
      docker build \
      --build-arg DOCK_JDK_VER="$DOCK_JDK_VER" \
      --build-arg SONAR_HOST_URL="$SONAR_HOST_URL" \
      --build-arg SONAR_AUTH_TOKEN="$SONAR_AUTH_TOKEN" \
      --build-arg SONAR_SCANNER_OPTS="$SONAR_SCANNER_OPTS" \
      --build-arg SONAR_RUNNER_HOME="$SONAR_RUNNER_HOME" \
      --build-arg SONAR_AUTH_KEY="$CI_PROJECT_PATH_SLUG" \
      --build-arg SONAR_PROJ_NAME="$CI_PROJECT_PATH" \
      --build-arg SONAR_PROJ_SUBNAME="$SONAR_PROJ_SUBNAME" \
      --build-arg CI_COMMIT_SHA="$CI_COMMIT_SHA" \
      --build-arg CI_COMMIT_REF_NAME="$REPORT_REF_NAME" \
      --build-arg CI_PROJECT_ID="$CI_PROJECT_ID" \
      --build-arg CI_DISABLE_REPORT="$REPORT_DISABLE" \
      --build-arg CI_ALLISSUE_REPORT="$REPORT_ALLISSUE" \
      --build-arg CI_MERGE_REQUEST_IID="$CI_MERGE_REQUEST_IID" \
      -f Dockerfile.$REPORT_ENV \
      -t $REPORT_ENV .
    - docker image rm -f $REPORT_ENV
    - echo "$REPORT_ENV DONE"

# Job Sonar Template
.inline-sonar-template:
  <<: *sonar-definition
  variables:
    REPORT_ENV: "sonar-gategit-report"
    REPORT_DISABLE: "sonar.gitlab.disable_global_comment"
    REPORT_ALLISSUE: "false"
    REPORT_REF_NAME: "$CI_COMMIT_REF_NAME"

.global-sonar-template:
  <<: *sonar-definition
  variables:
    REPORT_ENV: "sonar-sonarqube-report"
    REPORT_ALLISSUE: "true"
    REPORT_REF_NAME: "$CI_COMMIT_REF_NAME"

#Branch Refs Template
.branch-inline-sonar-template:
  except: &branch-inline-sonar-definition
    refs:
      - develop
      - sandbox
      - staging
      - master

.branch-global-sonar-template:
  only:
    refs: &branch-global-sonar-definition
      - develop
      - master

# Define Job
ftc-sonar-inline:
  extends: .inline-sonar-template
  variables:
    SONAR_PROJ_SUBNAME: "feed_the_cat"
  except: *branch-inline-sonar-definition
  only:
    changes:
      - .gitlab-ci.yml
      - Dockerfile*
      - Projects/feed_the_cat

ftc-sonar-global:
  extends: .global-sonar-template
  variables:
    SONAR_PROJ_SUBNAME: "feed_the_cat"
  only:
    refs: *branch-global-sonar-definition
    changes:
      - .gitlab-ci.yml
      - Dockerfile*
      - Projects/feed_the_cat

glt-sonar-inline:
  extends: .inline-sonar-template
  variables:
    SONAR_PROJ_SUBNAME: "galaxy_tower"
  except: *branch-inline-sonar-definition
  only:
    changes:
      - .gitlab-ci.yml
      - Dockerfile*
      - Projects/galaxy_tower

glt-sonar-global:
  extends: .global-sonar-template
  variables:
    SONAR_PROJ_SUBNAME: "galaxy_tower"
  only:
    refs: *branch-global-sonar-definition
    changes:
      - .gitlab-ci.yml
      - Dockerfile*
      - Projects/galaxy_tower

gtb-sonar-inline:
  extends: .inline-sonar-template
  variables:
    SONAR_PROJ_SUBNAME: "guess_the_box"
  except: *branch-inline-sonar-definition
  only:
    changes:
      - .gitlab-ci.yml
      - Dockerfile*
      - Projects/guess_the_box

gtb-sonar-global:
  extends: .global-sonar-template
  variables:
    SONAR_PROJ_SUBNAME: "guess_the_box"
  only:
    refs: *branch-global-sonar-definition
    changes:
      - .gitlab-ci.yml
      - Dockerfile*
      - Projects/guess_the_box

jmf-sonar-inline:
  extends: .inline-sonar-template
  variables:
    SONAR_PROJ_SUBNAME: "jumping_frog"
  except: *branch-inline-sonar-definition
  only:
    changes:
      - .gitlab-ci.yml
      - Dockerfile*
      - Projects/jumping_frog

jmf-sonar-global:
  extends: .global-sonar-template
  variables:
    SONAR_PROJ_SUBNAME: "jumping_frog"
  only:
    refs: *branch-global-sonar-definition
    changes:
      - .gitlab-ci.yml
      - Dockerfile*
      - Projects/jumping_frog

mtc-sonar-inline:
  extends: .inline-sonar-template
  variables:
    SONAR_PROJ_SUBNAME: "match_the_card"
  except: *branch-inline-sonar-definition
  only:
    changes:
      - .gitlab-ci.yml
      - Dockerfile*
      - Projects/match_the_card

mtc-sonar-global:
  extends: .global-sonar-template
  variables:
    SONAR_PROJ_SUBNAME: "match_the_card"
  only:
    refs: *branch-global-sonar-definition
    changes:
      - .gitlab-ci.yml
      - Dockerfile*
      - Projects/match_the_card

ptb-sonar-inline:
  extends: .inline-sonar-template
  variables:
    SONAR_PROJ_SUBNAME: "pop_the_baloon"
  except: *branch-inline-sonar-definition
  only:
    changes:
      - .gitlab-ci.yml
      - Dockerfile*
      - Projects/pop_the_baloon

ptb-sonar-global:
  extends: .global-sonar-template
  variables:
    SONAR_PROJ_SUBNAME: "pop_the_baloon"
  only:
    refs: *branch-global-sonar-definition
    changes:
      - .gitlab-ci.yml
      - Dockerfile*
      - Projects/pop_the_baloon

shtb-sonar-inline:
  extends: .inline-sonar-template
  variables:
    SONAR_PROJ_SUBNAME: "shoot_the_blocks"
  except: *branch-inline-sonar-definition
  only:
    changes:
      - .gitlab-ci.yml
      - Dockerfile*
      - Projects/shoot_the_blocks

shtb-sonar-global:
  extends: .global-sonar-template
  variables:
    SONAR_PROJ_SUBNAME: "shoot_the_blocks"
  only:
    refs: *branch-global-sonar-definition
    changes:
      - .gitlab-ci.yml
      - Dockerfile*
      - Projects/shoot_the_blocks

srtb-sonar-inline:
  extends: .inline-sonar-template
  variables:
    SONAR_PROJ_SUBNAME: "sort_the_box"
  except: *branch-inline-sonar-definition
  only:
    changes:
      - .gitlab-ci.yml
      - Dockerfile*
      - Projects/sort_the_box

srtb-sonar-global:
  extends: .global-sonar-template
  variables:
    SONAR_PROJ_SUBNAME: "sort_the_box"
  only:
    refs: *branch-global-sonar-definition
    changes:
      - .gitlab-ci.yml
      - Dockerfile*
      - Projects/sort_the_box

stc-sonar-inline:
  extends: .inline-sonar-template
  variables:
    SONAR_PROJ_SUBNAME: "star_catcher"
  except: *branch-inline-sonar-definition
  only:
    changes:
      - .gitlab-ci.yml
      - Dockerfile*
      - Projects/star_catcher

stc-sonar-global:
  extends: .global-sonar-template
  variables:
    SONAR_PROJ_SUBNAME: "star_catcher"
  only:
    refs: *branch-global-sonar-definition
    changes:
      - .gitlab-ci.yml
      - Dockerfile*
      - Projects/star_catcher

wam-sonar-inline:
  extends: .inline-sonar-template
  variables:
    SONAR_PROJ_SUBNAME: "whack_a_mole"
  except: *branch-inline-sonar-definition
  only:
    changes:
      - .gitlab-ci.yml
      - Dockerfile*
      - Projects/whack_a_mole

wam-sonar-global:
  extends: .global-sonar-template
  variables:
    SONAR_PROJ_SUBNAME: "whack_a_mole"
  only:
    refs: *branch-global-sonar-definition
    changes:
      - .gitlab-ci.yml
      - Dockerfile*
      - Projects/whack_a_mole